subcuencas_3 <- subcuencas %>% filter(SUBCUENCA %in% c("L. Totolzin", "R. Cazones", "R. Salado")) %>% select(SUBCUENCA)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(sf, stars)
Passerina <- readr::read_csv("DATOS/Tablas/Passerina_versicolor.csv") %>% sf::st_as_sf(coords = c("longitude", "latitude"))
Diglossa <- readr::read_csv("DATOS/Tablas/Diglossa_baritula.csv") %>% sf::st_as_sf(coords = c("longitude", "latitude"))
st_crs(Passerina) <- st_crs("+proj=longlat +datum=WGS84")
st_crs(Diglossa) <- st_crs("+proj=longlat +datum=WGS84")
sf::write_sf(Passerina, "Passerina.shp")
sf::write_sf(Diglossa, "Diglossa.shp")
